### ISSUE TITLE
Create a public github action to allow usage from other repos

### ISSUE THREAD

**Issue by harlantwood** [holochain-ci/matrix#9]
Config would be something like:

```yaml
      - uses: holochain-ci/matrix@v1
        with:
          github_orgs: 
            - holochain
            - holo-host
          github_repos: 
            - alice23857235/holochain-awesome
```
